/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package coding.interview.question;

import java.util.LinkedList;
import java.util.List;
import java.util.Iterator;

import coding.interview.question.question1.Solution;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }


    public static void main(String[] args) {

    }
}
